#At this moment those placeholders are in the messages supported:
#
# %playername%
# %displayname%
# %server%
#
# on server switch there is one extra placeholder: %prevserver%

settings:
  notifyJoin: true
  delayJoinMessage: 25 #long
  notifyQuit: true
  notifyServerSwitch: true